In [3]:
#boolean indexing om 1 d array
import numpy as np
a=np.array(['t','a','b','d','g','j','f','u'])
b=np.random.randint(1,20,8)
print(a)
print(b)


['t' 'a' 'b' 'd' 'g' 'j' 'f' 'u']
[ 5 15 19 18 19 16 14  3]


In [4]:
print(b>10)

[False  True  True  True  True  True  True False]


In [6]:
bool_arr=b>10
print(bool_arr)
new_arr=b[bool_arr]
print(new_arr)

[False  True  True  True  True  True  True False]
[15 19 18 19 16 14]


In [7]:
new_arr=b[b>10]
print(new_arr)

[15 19 18 19 16 14]


In [9]:
new_arr=b[(b>10) & (b<18)]
print(new_arr)

[15 16 14]


In [10]:
print(b)
c=b
c

[ 5 15 19 18 19 16 14  3]


array([ 5, 15, 19, 18, 19, 16, 14,  3])

In [11]:
c[:3]=19
print(c)
c[c>15]=100
print(c)

[19 19 19 18 19 16 14  3]
[100 100 100 100 100 100  14   3]


In [12]:
print(b)
print(b[b==100])
print(b)

[100 100 100 100 100 100  14   3]
[100 100 100 100 100 100]
[100 100 100 100 100 100  14   3]


In [13]:
ind=np.where(b==100)
print(ind)

(array([0, 1, 2, 3, 4, 5], dtype=int64),)


In [14]:
print(a)
print(b)

['t' 'a' 'b' 'd' 'g' 'j' 'f' 'u']
[100 100 100 100 100 100  14   3]


In [16]:
ind=np.where(b==100)
print(ind)
print(a[ind])

(array([0, 1, 2, 3, 4, 5], dtype=int64),)
['t' 'a' 'b' 'd' 'g' 'j']


In [17]:
import numpy as np
a=np.random.randint(1,30,(5,6))
print(a)

[[ 6 24 25  6 13 15]
 [27 26 24 12  3  6]
 [12 21  6 15 24 26]
 [23 13  2 15 16 17]
 [ 8 22 27 21 13 20]]


In [19]:
bool_arr=a>20
print(bool_arr)

[[False  True  True False False False]
 [ True  True  True False False False]
 [False  True False False  True  True]
 [ True False False False False False]
 [False  True  True  True False False]]


In [20]:
ans=a[bool_arr]
print(ans)

[24 25 27 26 24 21 24 26 23 22 27 21]


In [21]:
b=a
print(a)

[[ 6 24 25  6 13 15]
 [27 26 24 12  3  6]
 [12 21  6 15 24 26]
 [23 13  2 15 16 17]
 [ 8 22 27 21 13 20]]


In [22]:
b[bool_arr]=100
print(b)

[[  6 100 100   6  13  15]
 [100 100 100  12   3   6]
 [ 12 100   6  15 100 100]
 [100  13   2  15  16  17]
 [  8 100 100 100  13  20]]


In [26]:
c=np.random.randint(1,10,(2,2))
print(c)
c_bool=np.array([[True, False],[False, True],[True, True]])
print(c_bool)
print(b)
bool_

[[1 7]
 [4 5]]
[[ True False]
 [False  True]
 [ True  True]]
