In [1]:
import numpy as np
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print(y)


[[7 4 9]
 [2 1 1]
 [8 7 4]]
[[3 3 9]
 [5 7 4]
 [8 7 9]]


In [3]:
import numpy as np
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print(y)
ans=x-y

[[4 7 1]
 [4 6 8]
 [2 7 4]]
[[2 5 3]
 [7 5 3]
 [8 4 8]]


In [4]:
print(ans)
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3))
print(x)
print(y)
print(x-y)


[[ 2  2 -2]
 [-3  1  5]
 [-6  3 -4]]
[[6 8 9]
 [3 4 4]
 [8 6 8]]
[7 7 1]
[[-1  1  8]
 [-4 -3  3]
 [ 1 -1  7]]


In [5]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(2,3))
print(x)
print(y)
y=np.transpose(y)

[[1 6]
 [8 4]
 [4 1]]
[[7 5 1]
 [9 7 4]]
