In [4]:
import numpy as np
li=[1,2,3,4,5]
array=np.array(li)
print(li)
print(array)
print(array.data)
print(array.shape)
print(array.dtype)
print(array.strides)


[1, 2, 3, 4, 5]
[1 2 3 4 5]
(5,)
int32
(4,)


In [9]:
#creating 2d array
import numpy as  np
li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

arr_2d=np.array(li_2d)

print(li_2d)
print(arr_2d)
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
int32
(16, 4)


In [15]:
#accessing element in 1d array
#in 1d array slicing and indexing works same as list
import numpy as np
li=[1,2,3,4,5]
array=np.array(li)
print(li)
print(array)
print(li[3])
print(array[3])
print(li[1:4])
print(array[1:4])

[1, 2, 3, 4, 5]
[1 2 3 4 5]
4
4
[2, 3, 4]
[2 3 4]


In [26]:
#accessing element in 2d array
import numpy as  np
li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

arr_2d=np.array(li_2d)

print(li_2d)
print(arr_2d)
print(li_2d[2][1])
print(arr_2d[2][1])
#we can write the above line of code like this also
print(arr_2d[2,1])
print(li_2d[1][0:3])
#print(arr_2d[1][1, :3])


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
10
10
10
[5, 6, 7]


In [29]:
print(li_2d[0:3][2])
x=li_2d[0:3]
print(x)
print(x[2])
#array work differently from list in numpy
print(arr_2d[0:3,3])

[9, 10, 11, 12]
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]
[ 4  8 12]


In [30]:
print(arr_2d[2:4, 1:3])
print(li_2d[2:4][1:3])

[[10 11]
 [14 15]]
[[13, 14, 15, 16]]


In [ ]:
#we can't get columns chunks in list we have to use iteration , so we should use numpy array to get columns chunks
