In [1]:
import numpy as np
li=[1,2,3,4,5,6,7]
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)
print(a)
print(b)

[ 5  7 13 17 11]
[ 4 17 17 14 15]


In [2]:
li=[i+1 for i in li]
li

[2, 3, 4, 5, 6, 7, 8]

In [3]:
a=a+1
a

array([ 6,  8, 14, 18, 12])

In [4]:
c=a+b
c

array([10, 25, 31, 32, 27])

In [5]:
d=a-b
d

array([ 2, -9, -3,  4, -3])

In [6]:
e=a*b
e

array([ 24, 136, 238, 252, 180])

In [7]:
f=a**b
f

array([       1296,           0,  -586285056, -1614004224, -1073741824],
      dtype=int32)

In [8]:
f=a/b
f

array([1.5       , 0.47058824, 0.82352941, 1.28571429, 0.8       ])

In [9]:
g=a//b
g

array([1, 0, 0, 1, 0], dtype=int32)

In [10]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax)

[ 6  8 14 18 12]
58
11.6
6
0
18
<built-in method argmax of numpy.ndarray object at 0x000001824739DAB0>


In [11]:
print(a)
print(b)
print(a>b)
print(a<b)
print(a==b)
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))


[ 6  8 14 18 12]
[ 4 17 17 14 15]
[ True False False  True False]
[False  True  True False  True]
[False False False False False]
[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


In [12]:
import numpy as np
a=np.random.randint(1,20,(3,3))
b=np.random.randint(1,20,(3,3))
print(a)
print(b)


[[18 16 13]
 [16  6 15]
 [13 15 10]]
[[13 17 16]
 [11  8  5]
 [14 15 14]]


In [13]:
a=a+1
b=b+1
print(a)
print(b)


[[19 17 14]
 [17  7 16]
 [14 16 11]]
[[14 18 17]
 [12  9  6]
 [15 16 15]]


In [14]:
print(a+b)

[[33 35 31]
 [29 16 22]
 [29 32 26]]


In [15]:
print(a-b)

[[ 5 -1 -3]
 [ 5 -2 10]
 [-1  0 -4]]


In [16]:
print(a*b)
print(a**b)
print(a/b)
print(a//b)
print(a)

[[266 306 238]
 [204  63  96]
 [210 256 165]]
[[ -281002215 -1482188255  -586285056]
 [ 1333592769    40353607    16777216]
 [ -769949696           0  1632031715]]
[[1.35714286 0.94444444 0.82352941]
 [1.41666667 0.77777778 2.66666667]
 [0.93333333 1.         0.73333333]]
[[1 0 0]
 [1 0 2]
 [0 1 0]]
[[19 17 14]
 [17  7 16]
 [14 16 11]]


In [18]:
print(a)
print(b)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[[19 17 14]
 [17  7 16]
 [14 16 11]]
[[14 18 17]
 [12  9  6]
 [15 16 15]]
131
14.555555555555555
7
4
19
0


In [17]:
print(b)
print(b.sum())
print(b.mean())
print(b.min())
print(b.argmin())
print(b.max())
print(b.argmax())

[[14 18 17]
 [12  9  6]
 [15 16 15]]
122
13.555555555555555
6
5
18
1


In [19]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a,b))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
print(a)
print(b)
print(a>b)
p