In [1]:
#numpy is a multidimensional array
#advantage of numpy over list:
#1.memory utilized by numby is less than list, we can see that by below examples.
import numpy as np
li_arr=[i for i in range (0,100)]
np_arr=np.arange (100)
print(li_arr)
print(np_arr)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [2]:
# size of one element in numpy array is 8 byte in mac and 4 byte in window compiler, here is proof
print(np_arr.itemsize)
print(np_arr.itemsize*np_arr.size)

4
400


In [3]:
#size of one element in list
import sys
a=10
print(sys.getsizeof(a))
print(sys.getsizeof(1)*len(li_arr))

28
2800


In [4]:
#2. numpy execution time is much faster than the list
import time
import numpy as np
size=100000
#add elements of array a and b
def addition_using_list():
    t1=time.time()
    a=range(size)
    b=range(size)
    c=[a[i]+b[i] for i in range (size)]
    t2=time.time()
    return(t2-t1)
def addition_using_numpy():
    t1=time.time()
    a=np.arange(size)
    b=np.arange(size)
    c=a+b
    t2=time.time()
    return(t2-t1)
t_list=addition_using_list()
t_numpy=addition_using_numpy()
print('list= ',t_list*1000)
print('numpy= ',t_numpy*1000)

list=  52.85811424255371
numpy=  0.6318092346191406


In [ ]:
#other advantages are convinence to use, functions are optimized.

In [5]:
#creating numpy arrays
import numpy as np
a=[1,2,3]
b=np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
#numpy arry contain element of same type which we call homogenous array
a=[1,2,3,4,'5',6]
b=np.array(a, dtype=int)
print(b)

[1 2 3 4 5 6]


In [8]:
a=[1,2,3,4,5]
b=np.array(a*3)
print(b)

[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


In [10]:
#creating2-d array
b=np.ones((2,3), dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
b=np.ones(1)
b

array([1.])

In [13]:
b=np.zeros((3,4), dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
b=np.full(3,5)
b

array([5, 5, 5])

In [15]:
b=np.full(3,5,dtype=float)
b

array([5., 5., 5.])

In [16]:
b=np.full((3,5),5,dtype=float)
b

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])