In [21]:
import numpy as np
point_array=np.linspace(0,5,10)
print(point_array)
print(point_array[1]-point_array[0])
print(point_array[3]-point_array[2])
round_off_value=np.around(point_array,decimals=2)
print(*round_off_value, sep = "\n")

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
0.5555555555555556
0.5555555555555556
0.0
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44
5.0


In [31]:
import numpy as np
array=np.arange(1,11,1)
print(array)
bool_arr=(array>2) &(array<9)
print(bool_arr)
new_arr=np.logical_not(bool_arr)
print(*new_arr, sep = "\n")


[ 1  2  3  4  5  6  7  8  9 10]
[False False  True  True  True  True  True  True False False]
True
True
False
False
False
False
False
False
True
True


In [33]:
age=([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
a=np.array(age)
b=np.array(height)
print(a)
print(b)


[15 17 19 20 14 21 16 19 13 20 22 23 21 16 18 19 20 15 17 18]
[156 144 180 162 152 157 154 155 151 150 158 179 126 182 183 154 159 160
 172 149]


In [45]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
ind=np.where(height>155)
age=age[ind]
height=height[ind]
l=len(age)
for i in range(l):
    print(age[i],height[i],sep=" ")

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


In [44]:
import numpy as np
a=np.array([[21,20 ,19 ,18, 17],[16, 15 ,14, 13, 12],[11, 10,  9 , 8 , 7], [ 6 , 5,  4,  3,  2]])
print(a)
b = a[a[:,0].argsort()]
print(b)




[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]
[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [32]:
import numpy as np
l=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
b=np.array(l)
ind=np.where((b>=3)&(b<=8))
a=[-1*i for i in b[ind] ]
b[2:8]=a[:]
for i in b:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10
