In [4]:
#np.arange
import numpy as np
b=np.arange(10)
print(b)
b=np.arange(2,10)
print(b)
b=np.arange(2,20,2)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


In [9]:
import numpy as np
b=np.linspace(10, 50)
print(b)
b=np.linspace(10,40,50, dtype=int, endpoint=False)
print(b)

[10.         10.81632653 11.63265306 12.44897959 13.26530612 14.08163265
 14.89795918 15.71428571 16.53061224 17.34693878 18.16326531 18.97959184
 19.79591837 20.6122449  21.42857143 22.24489796 23.06122449 23.87755102
 24.69387755 25.51020408 26.32653061 27.14285714 27.95918367 28.7755102
 29.59183673 30.40816327 31.2244898  32.04081633 32.85714286 33.67346939
 34.48979592 35.30612245 36.12244898 36.93877551 37.75510204 38.57142857
 39.3877551  40.20408163 41.02040816 41.83673469 42.65306122 43.46938776
 44.28571429 45.10204082 45.91836735 46.73469388 47.55102041 48.36734694
 49.18367347 50.        ]
[10 10 11 11 12 13 13 14 14 15 16 16 17 17 18 19 19 20 20 21 22 22 23 23
 24 25 25 26 26 27 28 28 29 29 30 31 31 32 32 33 34 34 35 35 36 37 37 38
 38 39]


In [ ]:
# np.arange-control over step value
#np.linspace-control over number of sample to be generated

In [10]:
#square matrix
b=np.identity(3)


print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#rectangualar matrix
b=np.eye(3,4)
print(b)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [12]:
#range is always from 0-1
b=np.random.rand(3)
print(b)

[0.62598335 0.78870013 0.65664903]


In [13]:
#we can increase the range value by multiplying
b=np.random.rand(10)*10
print(b)

[6.02925107 7.72108799 2.15543295 7.80118885 2.00950222 4.13426373
 6.09706127 6.505552   8.43610206 3.96661006]


In [ ]:
b=np.random.randit